config/routes.rb
Rails.application.routes.draw do
    resources :users
    get 'login' => 'sessions#new'
    post 'login' => 'sessions#create'
    delete 'logout' => 'sessions#destroy'

    namespace :trucking do
        root to: 'dashboard#index', as: 'dashboard'
    end

    namespace :supplier do
        root to: 'dashboard#index', as: 'dashboard'
        get 'pricerocket_history' => 'text_history#index'
        resources :retailers
        resources :suppliers
        resources :truckings
        resources :fuel_prices
        resources :contacts
        get 'mass_send/index'
        match '/mass_send' => 'mass_send#mass_send_texts', via: :get
        match '/mass_send' => 'mass_send#mass_send_texts', via: :post
        post 'search_query' => 'contacts#search_query'
    end

    namespace :retailer do
        root to: 'dashboard#index', as: 'dashboard'
        resources :stations
        resources :tanks
    end

    namespace :admin do
        root to: 'dashboard#index', as: 'dashboard'
        resources :retailers
        resources :suppliers
        resources :truckings
        resources :users
        resources :stations do
            resources :tanks
        end
    end

    get 'home/index'
    get 'home/minor'

    root to: 'home#index'
end

app/controllers/admin/retailers_controller.rb
class Admin::RetailersController < Admin::ApplicationController
    before_action :set_retailer, only: [:edit, :update]
    def index
        @retailers = User.all.where(role: 1)
    end

    def new
        @retailer = User.new
    end

    def create
    end

    def edit
    end

    def update
    end

    private

    def set_retailer
        @retailer = User.find(params[:id])
    end
end

app/controllers/admin/suppliers_controller.rb
class Admin::SuppliersController < Admin::ApplicationController
    before_action :set_supplier, only: [:edit, :update]
    def index
        @suppliers = User.all.where(role: 2)
    end

    def new
        @supplier = User.new
    end

    def create
    end

    def edit
    end

    def update
    end

    private

    def set_supplier
        @supplier = User.find(params[:id])
    end
end

app/controllers/retailer/application_controller.rb
class Retailer::ApplicationController < LoginrequiredController
    before_action :authenticate_retailer!

    def index
    end

    private

    def dashboard_path
        if current_user.admin?
            admin_dashboard_path
        elsif current_user.supplier?
            supplier_dashboard_path
        elsif current_user.trucking?
            trucking_dashboard_path
        end
    end

    def authenticate_retailer!
        unless current_user.retailer?
            redirect_to dashboard_path, alert: 'You are not authorized to access that section.'
        end
    end
end

app/controllers/retailer/dashboard_controller.rb
class Retailer::DashboardController < Retailer::ApplicationController
    def index
    end
end

app/controllers/retailer/stations_controller.rb
class Retailer::StationsController < Retailer::ApplicationController
    before_action :set_station, only: [:show, :edit, :update, :destroy]

    def index
        @stations = Station.all
    end

    def show
    end

    def new
        @station = Station.new
    end

    def edit
    end

    def create
        @station = Station.new(station_params)
        @station.retailer = current_user
        if @station.save
            redirect_to retailer_station_path(@station), notice: 'Station was successfully created.'
        else
            render :new
        end
    end

    def update
        if @station.update(station_params)
            redirect_to retailer_station_path(@station), notice: 'Station was successfully updated.'
        else
            render :edit
        end
    end

    def destroy
        @station.destroy
        redirect_to retailer_stations_url, notice: 'Station was successfully destroyed.'
    end

    private

    def set_station
        @station = Station.find(params[:id])
    end

    def station_params
        params.require(:station).permit(:brand, :business_name, :tax_id, :phone_number, :contact_person, :cell_number, :address1, :address2, :city, :state, :zip, :station_reg_number, :retailer_id)
    end
end

app/controllers/retailer/tanks_controller.rb
class Retailer::TanksController < Retailer::ApplicationController
    before_action :set_station
    before_action :set_tank, only: [:show, :edit, :update, :destroy]

    def set_station
        @station = Station.find(params[:station_id])
    end

    def index
        @tanks = @station.tanks
    end

    def show
    end

    def new
        @tank = @station.tanks.build
    end

    def edit
    end

    def create
        @tank = @station.tanks.create(tank_params)
        redirect_to retailer_station_path(@station)
    end

    def update
        if @tank.update(tank_params)
            redirect_to retailer_station_tank_path(@station, @tank)
        else
            render 'edit'
        end
    end

    def destroy
        @tank.destroy
        redirect_to retailer_station_tanks_path(@station), notice: 'Tank was successfully destroyed.'
    end

    private

    def set_tank
        @tank = @station.tanks.find(params[:id])
    end

    def tank_params
        params.require(:tank).permit(:type_of_fuel, :size, :registration_id, :station_id)
    end
end

app/controllers/supplier/application_controller.rb
class Supplier::ApplicationController < LoginrequiredController
    before_action :authenticate_supplier!

    private

    def dashboard_path
        if current_user.admin?
            admin_dashboard_path
        elsif current_user.retailer?
            retailer_dashboard_path
        elsif current_user.trucking?
            trucking_dashboard_path
        end
    end

    def authenticate_supplier!
        unless current_user.supplier?
            redirect_to dashboard_path, alert: 'You are not authorized to access that section.'
        end
    end
end

app/controllers/supplier/contacts_controller.rb
class Supplier::ContactsController < Supplier::ApplicationController
    before_action :set_contact, only: [:edit, :update, :destroy, :show]

    def index
        @contacts = current_user.contacts.all.order('created_at DESC')
        @contact = current_user.contacts.build
    end

    def new
        @contact = current_user.contacts.build
        @latest_contact = current_user.contacts.last
    end

    def create
        @contact = current_user.contacts.new(contacts_params)
        respond_to do |format|
            format.js do
                if @contact.save
                    @contacts = current_user.contacts.all.order('created_at DESC')
                    flash.now[:notice] = 'Retailer has been successfully added.'
                    render 'success'
                else
                    render 'create'
                end
            end
        end
    end

    def show
        @contact_prices = @contact.retail_prices.all.order('created_at DESC').offset(1)
        @latest_price = @contact.retail_prices.last
    end

    def edit
    end

    def update
        if @contact.update(contacts_params)
            flash[:notice] = 'Contact successfully Updated.'
            redirect_to supplier_contacts_path
        else
            flash.now[:alert] = 'Something went wrong. Check your form and re-try.'
            render 'edit'
        end
    end

    def destroy
    end

    private

    def contacts_params
        params.require(:contact).permit(:first_name, :last_name, :business_name, :phone_number, :cell_number, :street_address, :apt_suite, :city, :state, :zip_code, :in_biz, :email, :c_regular, :c_medium, :c_premium, :c_diesel, :c_delivery)
    end

    def set_contact
        @contact = current_user.contacts.find(params[:id])
    end
end

app/controllers/supplier/dashboard_controller.rb
class Supplier::DashboardController < Supplier::ApplicationController
    def index
        @latest_fuel_price = current_user.fuel_prices.last
        last_month = Time.zone.now - 1.month
        @texts = current_user.pricerockets.where('created_at >= ? and created_at <= ?', Time.now.beginning_of_month, Time.now.end_of_month)
        @prev_texts = current_user.pricerockets.where('created_at >= ? and created_at <= ?', last_month.beginning_of_month, last_month.end_of_month)
    end
end

app/controllers/supplier/fuel_prices_controller.rb
class Supplier::FuelPricesController < Supplier::ApplicationController
    before_action :set_fuel_price, only: [:edit, :update]
    before_action :set_twilio, only: [:create, :edit, :update]

    def index
        @fuel_prices = current_user.fuel_prices.all.order('created_at DESC')
        @latest_fuel_price = current_user.fuel_prices.last
        @fuel_price = current_user.fuel_prices.build
        @fuel_price.fuel_products.build
    end

    def new
        @fuel_price = current_user.fuel_prices.build
        @fuel_price.fuel_products.build
    end

    def create
        @fuel_price = current_user.fuel_prices.new(fuel_price_params)
        respond_to do |format|
            format.js do
                if @fuel_price.save
                    @fuel_prices = current_user.fuel_prices.all.order('created_at DESC')
                    @fuel = nil
                    current_user.retailers.each do |retailer|
                        @retail_price = retailer.retail_prices.create
                        retailer.fuel_formulas.sort.each do |formula|
                            current_user.fuel_prices.last.fuel_products.sort.each do |product|
                                if formula.fuel == product.fuel
                                    @fuel = product.fuel
                                    @retail_price.retail_products.create(fuel: @fuel, price: product.price + formula.margin)
                                end
                            end
                        end
                        products = []
                        @retail_price.retail_products.each do |product|
                            products << product.fuel + ' ' + ':' + ' ' + '$' + product.price.to_s
                        end
                        @pricerocket = current_user.pricerockets.create(to: retailer.cell_number, body: "Hey there! #{retailer.first_name}. #{current_user.first_name} from #{current_user.business_name} just updated their Fuel Price. Their current Fuel price is #{products.join(', ')}")
                        @client.messages.create(
                            from: '+18482299159',
                            to: "+1#{retailer.cell_number}",
                            body: "Hey there! #{retailer.first_name}. #{current_user.first_name} from #{current_user.business_name} just updated their Fuel Price. Their current Fuel price is #{products.join(', ')}"
                        )
                        @pricerocket.sent!
                    end
                    flash.now[:notice] = "You have successfully Added new Fuel Price. Petrohub sent out #{current_user.retailers.count} Text messages with updated price to your #{current_user.retailers.count} retailers."
                    render 'success'
                else
                    flash.now[:alert] = 'You need to add atleast one Fuel product price. You cannot have multiple same types of Fuel selected.'
                    render 'new'
               end
            end
        end
    end

    def edit
        respond_to do |format|
            format.js do
                render 'edit'
            end
        end
    end

    def update
        respond_to do |format|
            format.js do
                if @fuel_price.update(fuel_price_params)
                    @fuel_prices = current_user.fuel_prices.all.order('created_at DESC')
                    flash.now[:notice] = "Fuel Price has been successfully updated. And we sent out Text mesagges with updated price to #{current_user.contacts.count} retailers."
                    render 'success'
                else
                    render 'edit'
                end
            end
        end
    end

    private

    def fuel_price_params
        params.require(:fuel_price).permit(fuel_products_attributes: [:fuel, :price, :_destroy, :id])
    end

    def set_fuel_price
        @fuel_price = FuelPrice.find(params[:id])
    end

    def set_twilio
        require 'twilio-ruby'
        @client = Twilio::REST::Client.new ENV['twilio_account_sid'], ENV['twilio_auth_token']
    end
end

app/controllers/supplier/mass_send_controller.rb
class Supplier::MassSendController < Supplier::ApplicationController
    before_action :set_twilio, only: [:mass_send_texts]

    def index
        @texts = current_user.pricerockets.where(status: 0)
    end

    def mass_send_texts
        @texts = current_user.pricerockets.where(status: 0) # and is latest entry
        @texts.all do |text|
            @client.messages.create(
                from: '+18482299159',
                to: text.to,
                body: "Hey there! #{find_contact(text.to).first_name}. #{current_user.first_name} from #{current.business_name} just updated the Gas price for today. Regular: $#{find_contact(text.to).retail_prices.last.r_regular}, Medium: $#{find_contact(text.to).retail_prices.last.r_medium},Premium: $#{find_contact(text.to).retail_prices.last.r_premium}, Diesel: $#{find_contact(text.to).retail_prices.last.r_diesel}"
            )
            text.sent!
        end
        redirect_to supplier_mass_send_index_path
    end

    private

    def find_contact(phone)
        @contact = current_user.contacts.find_by(cell_number: phone)
    end

    def set_twilio
        require 'twilio-ruby'
        @client = Twilio::REST::Client.new ENV['twilio_account_sid'], ENV['twilio_auth_token']
    end
end

app/controllers/supplier/suppliers_controller.rb
class Supplier::SuppliersController < Supplier::ApplicationController
  def index
  end
end

app/controllers/supplier/text_history_controller.rb
class Supplier::TextHistoryController < Supplier::ApplicationController
    def index
        @texts = current_user.pricerockets.all.order('created_at DESC')
    end
end

app/controllers/supplier/truckings_controller.rb
class Supplier::TruckingsController < Supplier::ApplicationController
  def index
  end
end

app/helpers/admin/retailers_helper.rb
module Admin::RetailersHelper
    def retailer_full_name(retailer)
        full_name = retailer.first_name + ' ' + retailer.last_name
        full_name
    end

    def roles
        [
            ['Pending', :pending],
            ['Retailer', :retailer],
            ['Supplier', :supplier],
            ['Trucking', :trucking]
        ]
    end

    def status
        [
            ['Inactive', :inactive],
            ['Active', :active],
            ['Denied', :denied],
            ['Archive', :archived]
        ]
    end
end

app/helpers/admin/suppliers_helper.rb
module Admin::SuppliersHelper
    def supplier_full_name(supplier)
        full_name = supplier.first_name + ' ' + supplier.last_name
        full_name
    end
end

app/helpers/retailer/application_helper.rb
module Retailer::ApplicationHelper
end

app/helpers/retailer/dashboard_helper.rb
module Retailer::DashboardHelper
end

app/helpers/retailer/stations_helper.rb
module Retailer::StationsHelper
end

app/views/supplier/retailers/_alert.html.erb
<% flash.each do |key, message| %>
<div class="alert alert-<%= key %>">
    <%= message %>
</div>
<% end %>

app/views/supplier/retailers/_edit_form.html.erb
<%= simple_form_for(@retailer, remote: true, url: supplier_retailer_path, :html => {:class => 'form-vertical' }) do |f| %>
<% flash.each do |key, message| %>
<div class="alert alert-<%= key %>">
    <%= message %>
</div>
<% end %>
<%= f.input :first_name, label: "First Name" %>
<%= f.input :last_name, label: "Last Name"%>
<%= f.input :business_name, label: "Business Name" %>
<%= f.input :email, label: "Email" %>
<%= f.input :cell_number, label: "Mobile Number" %>
<%= f.input :zip_code, label: "Zip Code" %>
<%= f.simple_fields_for :fuel_formulas do |fuel_formulas_form| %>
  <%= render partial: 'fuel_formulas_fields', locals: {f: fuel_formulas_form} %>
<% end %>

<%= link_to_add_fields "Add More", f, :fuel_formulas %>
  <div class="modal-footer">
    <%= f.button :submit, "Add", class: "btn btn-success"%>
  </div>
<%end%>

app/views/supplier/retailers/_form.html.erb
<%= simple_form_for(@retailer, remote: true, url: supplier_retailers_path, :html => {:class => 'form-vertical' }) do |f| %>
<% flash.each do |key, message| %>
<div class="alert alert-<%= key %>">
    <%= message %>
</div>
<% end %>
<%= f.input :first_name, label: "First Name" %>
<%= f.input :last_name, label: "Last Name"%>
<%= f.input :business_name, label: "Business Name" %>
<%= f.input :email, label: "Email" %>
<%= f.input :cell_number, label: "Mobile Number" %>
<%= f.input :zip_code, label: "Zip Code" %>
<%= f.simple_fields_for :fuel_formulas do |fuel_formulas_form| %>
  <%= render partial: 'fuel_formulas_fields', locals: {f: fuel_formulas_form} %>
<% end %>

<%= link_to_add_fields "Add More", f, :fuel_formulas %>
  <div class="modal-footer">
    <%= f.button :submit, "Add", class: "btn btn-success"%>
  </div>
<%end%>

app/views/supplier/retailers/_fuel_formulas_fields.html.erb
<div class="row">
<div class="col-md-6">
    <strong><%= f.input :fuel, label: "Fuel Type", :collection => fuel_types, class: "form-control select"%></strong>
</div>
<div class="col-md-3">
  <%= f.input :margin,label: "Margin", class: "form-control", placeholder: "+0.003" %>
</div>
<div class="col-md-3">
<%= f.hidden_field :_destroy %>
<%= link_to '#', class: "btn btn-danger btn-xs remove_fields" do %>
        <i class="fa fa-times"></i>
        <%end%>
</div>
</div>

app/views/supplier/retailers/_margin_table.html.erb
<div class="title">
    <h3 id="today">Margins for <%= @retailer.first_name %> (Above prices are based on this margin added to your Fuel Price)</h3>
</div>
<% if @retailer.fuel_formulas.empty? %>
<div class="col-lg-12">
    <div class="widget style1 red-bg">
        <div class="row">
            <div class="col-xs-3">
                <i class="fa fa-usd fa-5x"></i>
            </div>
            <div class="col-xs-8 text-right">
                <span>
                    <strong>No Fuel Margin Found</strong>
                </span>
                </h2>
            </div>
        </div>
    </div>
</div>
<%else%>
<% prices = {} %>
<% @retailer.fuel_formulas.each do |product| %>
<% prices[product.fuel] = product.margin %>
<%end%>
<div class="col-lg-3">
    <div class="widget style1" id="fuel_margins">
        <div class="row">
            <div class="col-xs-1">
                <i class="fa fa-usd fa-3x"></i>
            </div>
            <div class="col-xs-8 text-right">
                <span>
                    <strong>87 RFG E10</strong>
                </span>
                <h2 class="font-bold">
                    <% if prices.include? "87 RFG E10" %>
                    <%= add_or_minus(prices["87 RFG E10"])%>
                    <%else%>
                    ---/---
                    <%end%>
                </h2>
            </div>
        </div>
    </div>
</div>
<div class="col-lg-3">
    <div class="widget style1" id="fuel_margins">
        <div class="row">
            <div class="col-xs-1">
                <i class="fa fa-usd fa-3x"></i>
            </div>
            <div class="col-xs-8 text-right">
                <span>
                    <strong>89 RFG E10</strong>
                </span>
                <h2 class="font-bold">
                    <% if prices.include? "89 RFG E10" %>
                    <%= add_or_minus(prices["89 RFG E10"])%>
                    <%else%>
                    ---/---
                    <%end%>
                </h2>
            </div>
        </div>
    </div>
</div>

<div class="col-lg-3">
    <div class="widget style1" id="fuel_margins">
        <div class="row">
            <div class="col-xs-1">
                <i class="fa fa-usd fa-3x"></i>
            </div>
            <div class="col-xs-8 text-right">
                <span>
                    <strong>91 RFG E10</strong>
                </span>
                <h2 class="font-bold">
                    <% if prices.include? "91 RFG E10" %>
                    <%= add_or_minus(prices["91 RFG E10"])%>
                    <%else%>
                    ---/---
                    <%end%>
                </h2>
            </div>
        </div>
    </div>
</div>
<div class="col-lg-3">
    <div class="widget style1" id="fuel_margins">
        <div class="row">
            <div class="col-xs-1">
                <i class="fa fa-usd fa-3x"></i>
            </div>
            <div class="col-xs-8 text-right">
                <span>
                    <strong>93 RFG E10</strong>
                </span>
                <h2 class="font-bold">
                    <% if prices.include? "93 RFG E10" %>
                    <%= add_or_minus(prices["93 RFG E10"])%>
                    <%else%>
                    ---/---
                    <%end%>
                </h2>
            </div>
        </div>
    </div>
</div>
<div class="col-lg-3">
    <div class="widget style1" id="fuel_margins">
        <div class="row">
            <div class="col-xs-1">
                <i class="fa fa-usd fa-3x"></i>
            </div>
            <div class="col-xs-8 text-right">
                <span>
                    <strong>Low Sodium Diesel</strong>
                </span>
                <h2 class="font-bold">
                    <% if prices.include? "Low Sodium Diesel" %>
                    <%= add_or_minus(prices["Low Sodium Diesel"])%>
                    <%else%>
                    ---/---
                    <%end%>
                </h2>
            </div>
        </div>
    </div>
</div>
<div class="col-lg-3">
    <div class="widget style1" id="fuel_margins">
        <div class="row">
            <div class="col-xs-1">
                <i class="fa fa-usd fa-3x"></i>
            </div>
            <div class="col-xs-8 text-right">
                <span>
                    <strong>Dyed ULS Diesel</strong>
                </span>
                <h2 class="font-bold">
                    <% if prices.include? "Dyed ULS Diesel" %>
                    <%= add_or_minus(prices["Dyed ULS Diesel"])%>
                    <%else%>
                    ---/---
                    <%end%>
                </h2>
            </div>
        </div>
    </div>
</div>
<div class="col-lg-3">
    <div class="widget style1" id="fuel_margins">
        <div class="row">
            <div class="col-xs-1">
                <i class="fa fa-usd fa-3x"></i>
            </div>
            <div class="col-xs-8 text-right">
                <span>
                    <strong>Undyed ULS Diesel</strong>
                </span>
                <h2 class="font-bold">
                    <% if prices.include? "Undyed ULS Diesel" %>
                    <%= add_or_minus(prices["Undyed ULS Diesel"])%>
                    <%else%>
                    ---/---
                    <%end%>
                </h2>
            </div>
        </div>
    </div>
</div>
<div class="col-lg-3">
    <div class="widget style1" id="fuel_margins">
        <div class="row">
            <div class="col-xs-1">
                <i class="fa fa-usd fa-3x"></i>
            </div>
            <div class="col-xs-8 text-right">
                <span>
                    <strong>Jet Fuel</strong>
                </span>
                <h2 class="font-bold">
                    <% if prices.include? "Jet Fuel" %>
                    <%= add_or_minus(prices["Jet Fuel"])%>
                    <%else%>
                    ---/---
                    <%end%>
                </h2>
            </div>
        </div>
    </div>
</div>
<div class="col-lg-3">
    <div class="widget style1" id="fuel_margins">
        <div class="row">
            <div class="col-xs-1">
                <i class="fa fa-usd fa-3x"></i>
            </div>
            <div class="col-xs-8 text-right">
                <span>
                    <strong>Heating Oil</strong>
                </span>
                <h2 class="font-bold">
                    <% if prices.include? "Heating Oil" %>
                    <%= add_or_minus(prices["Heating Oil"])%>
                    <%else%>
                    ---/---
                    <%end%>
                </h2>
            </div>
        </div>
    </div>
</div>
<div class="col-lg-3">
    <div class="widget style1" id="fuel_margins">
        <div class="row">
            <div class="col-xs-1">
                <i class="fa fa-usd fa-3x"></i>
            </div>
            <div class="col-xs-8 text-right">
                <span>
                    <strong>Kerosene</strong>
                </span>
                <h2 class="font-bold">
                    <% if prices.include? "Kerosene" %>
                    <%= add_or_minus(prices["Kerosene"])%>
                    <%else%>
                    ---/---
                    <%end%>
                </h2>
            </div>
        </div>
    </div>
</div>
<%end%>

app/views/supplier/retailers/_retailers_tables.html.erb
<% @retailers.each do |retailer| %>
<div class="col-lg-6">

    <div class="contact-box">
        <%= link_to supplier_retailer_path(retailer) do %>
        <div class="col-sm-4">
            <div class="text-center">
                <%=image_tag( avatar_url(retailer), class: "img-circle m-t-xs img-responsive")%>
            </div>
        </div>
        <div class="col-sm-8">
            <h3>
                <strong><%= retailer_full_name(retailer)%></strong>
            </h3>
            <address>
              <strong><%= retailer.business_name %></strong><br>

              <strong>Name: </strong>
              <%= retailer_full_name(retailer)%><br>
              <strong>Email:</strong>
              <%= retailer.email%><br>
              <strong>Zip Code</strong>
              <%= retailer.zip_code %><br>
              <abbr title="Phone">
                  <strong>
                      <i class="fa fa-phone"></i>
                  </strong>
              </abbr>
              <%= retailer.cell_number %>
            </address>
          <span class="label"> Click to view Margins <br>and their Current Fuel Price.</span>
        </div>
        <%end%>
        <div class="clearfix"></div>

    </div>

</div>
<%end%>

app/views/supplier/retailers/create.js.erb
$('#RetailerModelBody').html("<%= escape_javascript(render partial: 'form', locals: { retailer: @retailer }) %>");

app/views/supplier/retailers/edit.js.erb
$('#RetailerModelBody').html("<%= escape_javascript(render partial: 'edit_form', locals: { retailer: @retailer }) %>");

app/views/supplier/retailers/edit_success.js.erb
$('#RetailerModelBody').html("<%= escape_javascript(render partial: 'alert') %>");
$('#RetailerMarginTable').html("<%= escape_javascript(render partial: 'margin_table') %>");
$('#RetailPriceTable').html("<%= escape_javascript(render partial: 'retail_price_table') %>");
$('#editRetailer').slideUp( "slow", function() {
    // Animation complete.
    $('#editRetailer').modal('toggle');
  });

app/views/supplier/retailers/index.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-12">
        <h2>Retailers</h2>
        <ol class="breadcrumb">
            <li>
                <%= link_to "Home", supplier_dashboard_path %>
            </li>
            <li class="active">
                <strong>Retailers</strong>
            </li>
            <%= link_to new_supplier_retailer_path, remote: true do %>
            <button type="button" class="btn btn-success pull-right" data-toggle="modal" data-target="#newRetailer">
                <i class="fa fa-user-plus"></i>
                <strong>&nbsp;New Retailer</strong>
            </button>
            <%end%>
        </ol>
    </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">

    <div class="row" id="RetailerTable">
        <%= render partial: 'retailers_tables', locals: { retailers: @retailers } %>
    </div>

</div>
<div class="modal inmodal" id="newRetailer" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content animated bounceInRight">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">&times;</span>
                    <span class="sr-only">Close</span>
                </button>
                <i class="fa fa-users modal-icon" style="color:#1ab394"></i>
                <h4 class="modal-title">Add New Retailer</h4>
                <span class="font-bold">Your Retailers will get text message of your latest price</span>
            </br>
            <span class="font-bold">As (your fuel price + the formula). Set the Formula for them below.</span>
        </div>
        <div class="modal-body" id="RetailerModelBody">
            <!--form -->
        </div>
    </div>
</div>
</div>

<% content_for :javascript do %>

<script type="text/javascript">

$(function () {

    $('.contact-box').each(function () {
        animationHover(this, 'pulse');
    });

});
</script>

<% end %>

app/views/supplier/retailers/show.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-12">
        <h2><strong>Current latest price for <%= @retailer.first_name %></strong></h2>
        <ol class="breadcrumb">
            <li class="active">
                <strong><%= @retailer.business_name.upcase %></strong>
            </li>
            <li class="active">
                <strong><%= retailer_full_name(@retailer) %></strong>
            </li>
            <li class="active">
                <strong><%= @retailer.email %></strong>
            </li>
            <li class="active">
                <i class="fa fa-phone"></i>&nbsp;<strong><%= @retailer.cell_number %></strong>
            </li>

            <%= link_to edit_supplier_retailer_path(@retailer), remote: true do %>
            <button type="button" class="btn btn-success pull-right" data-toggle="modal" data-target="#editRetailer">
                <i class="fa fa-plus"></i>
                <strong>&nbsp;Edit Retailer</strong>
            </button>
            <%end%>
        </ol>
    </div>
    <div class="col-lg-2"></div>
</div>

<div class="row" id="RetailPriceTable">
    <%= render partial: "retail_price_table", locals: {retailer: @retailer} %>
</div>
<br>
<br>

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-12">
        <h2><strong>Margins for <%= @retailer.first_name %></strong></h2>
    </div>
    <div class="col-lg-2"></div>
</div>


<!-- Margins-->
<div class="row" id="RetailerMarginTable">
    <%= render partial: 'margin_table', locals: { retailer: @retailer } %>
</div>


<div class="modal inmodal" id="editRetailer" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content animated bounceInRight">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">&times;</span>
                    <span class="sr-only">Close</span>
                </button>
                <i class="fa fa-usd modal-icon" style="color:#1ab394"></i>
                <h4 class="modal-title">Edit Retailer</h4>
                <span class="font-bold">Your Retailrs will get text message of your latest price</span>
            </br>
            <span class="font-bold">As (your fuel price + the Margin).</span>
        </div>
        <div class="modal-body" id="RetailerModelBody">
            <!-- form -->
        </div>
    </div>
</div>
</div>