config/routes.rb
Rails.application.routes.draw do
    resources :users
    get 'login' => 'sessions#new'
    post 'login' => 'sessions#create'
    delete 'logout' => 'sessions#destroy'

    namespace :trucking do
        root to: 'dashboard#index', as: 'dashboard'
    end

    namespace :supplier do
        root to: 'dashboard#index', as: 'dashboard'
        get 'pricerocket_history' => 'text_history#index'
        resources :retailers
        resources :suppliers
        resources :truckings
        resources :fuel_prices
        resources :contacts
        get 'mass_send/index'
        match '/mass_send' => 'mass_send#mass_send_texts', via: :get
        match '/mass_send' => 'mass_send#mass_send_texts', via: :post
        post 'search_query' => 'contacts#search_query'
    end

    namespace :retailer do
        root to: 'dashboard#index', as: 'dashboard'
        resources :stations
        resources :tanks
    end

    namespace :admin do
        root to: 'dashboard#index', as: 'dashboard'
        resources :retailers
        resources :suppliers
        resources :truckings
        resources :users
        resources :stations do
            resources :tanks
        end
    end

    get 'home/index'
    get 'home/minor'

    root to: 'home#index'
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::ApplicationController
    def index
        @users = User.all.order(:status)
    end
end

app/controllers/retailer/dashboard_controller.rb
class Retailer::DashboardController < Retailer::ApplicationController
    def index
    end
end

app/controllers/supplier/dashboard_controller.rb
class Supplier::DashboardController < Supplier::ApplicationController
    def index
        @latest_fuel_price = current_user.fuel_prices.last
        last_month = Time.zone.now - 1.month
        @texts = current_user.pricerockets.where('created_at >= ? and created_at <= ?', Time.now.beginning_of_month, Time.now.end_of_month)
        @prev_texts = current_user.pricerockets.where('created_at >= ? and created_at <= ?', last_month.beginning_of_month, last_month.end_of_month)
    end
end

app/controllers/trucking/dashboard_controller.rb
class Trucking::DashboardController < Trucking::ApplicationController
    def index
    end
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
    def user_full_name(user)
        full_name = user.first_name + ' ' + user.last_name
        full_name
    end
end

app/helpers/retailer/dashboard_helper.rb
module Retailer::DashboardHelper
end

app/helpers/supplier/dashboard_helper.rb
module Supplier::DashboardHelper
    def to_percentage(text)
        percentage = if text.nil?
                         0
                     else
                         text * 100 / 2000
                     end
        percentage.to_f
    end

    def calculate_average(_current_user)
        0
    end
end

app/helpers/trucking/dashboard_helper.rb
module Trucking::DashboardHelper
end

app/views/admin/dashboard/index.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2><%= current_user.first_name%>'s Dashboard'</h2>
        <ol class="breadcrumb">
            <li class="active">
                <strong>Home</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2"></div>
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-content">
                <div class="">
                    <%= link_to "New User", new_admin_user_path, class: "btn btn-primary"%>
                </div>
                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover">
                        <thead>
                            <tr>
                                <th>Date</th>
                                <th>Name</th>
                                <th>Email</th>
                                <th>Business Name</th>
                                <th>Phone Number</th>
                                <th>User Type</th>
                                <th>Status</th>
                                <th>Action</th>

                            </tr>
                        </thead>

                        <tbody>
                            <% @users.each do |user| %>
                            <tr>
                                <td><%=user.created_at.to_formatted_s(:short) %></td>
                                <td><%=user_full_name(user)%></td>
                                <td><%= user.email%></td>
                                <td><%=user.business_name%></td>
                                <td><%=user.phone_number%></td>
                                <td><%=link_to "#{user.role}", edit_admin_user_path(user), class: "btn btn-xs btn-#{user.pending? ? 'warning' : 'info'}"%></td>
                                <td><%=link_to "#{user.status}", edit_admin_user_path(user), class: "btn btn-xs btn-#{user.active? ? 'primary' : 'danger'}"%></td>
                                <td><%= link_to "View", edit_admin_user_path(user), class: "btn btn-xs btn-success"%></td>
                            </tr>
                        </tbody>
                        <%end%>
                    </table>

                </div>
            </div>
        </div>
    </div>